@startuml

title psu_capstone.agent_layer.agent

class Agent
class SpatialPooler
class TemporalMemory
class Column
class Synapse

Agent o-- "0..*" SpatialPooler : poolers
Agent o-- "0..*" TemporalMemory : memory
Agent ..> Column : creates
Agent ..> Synapse : creates

@enduml
