@startuml

title psu_capstone.agent_layer.brain

class Brain
class Field
class InputField
class OutputField
class ColumnField

Field <|-- InputField
InputField <|-- OutputField
Field <|-- ColumnField

Brain o-- "0..*" InputField : input_fields
Brain o-- "0..*" OutputField : output_fields
Brain o-- "0..*" ColumnField : column_fields
Brain o-- "0..*" Field : fields

@enduml
