@startuml

title psu_capstone.agent_layer.HTM

class Active
class Winner
class Predictive
class Bursting
class Learning
class Matching

class Field
class Synapse
class ApicalSynapse
class DistalSynapse
class ProximalSynapse
class Segment
class ApicalSegment
class Cell
class Column
class ColumnField
class InputField
class OutputField
class RDSEParameters

Active <|-- Segment
Learning <|-- Segment
Matching <|-- Segment

Active <|-- Cell
Winner <|-- Cell
Predictive <|-- Cell

Active <|-- Column
Predictive <|-- Column
Bursting <|-- Column

Synapse <|-- ApicalSynapse
Synapse <|-- DistalSynapse
Synapse <|-- ProximalSynapse

Segment <|-- ApicalSegment

Field <|-- ColumnField
Field <|-- InputField
InputField <|-- OutputField

Field o-- "0..*" Cell : cells
Synapse o-- Cell : source_cell
Segment o-- Cell : parent_cell
Segment o-- "0..*" Synapse : synapses
Cell o-- "0..*" Segment : segments
Cell ..> Field : distal_field
Cell ..> Field : apical_field
Column o-- "1..*" Cell : cells
Column o-- "0..*" ProximalSynapse : synapses
ColumnField o-- "1..*" Column : columns
ColumnField o-- "1..*" Field : input_fields
InputField ..> RDSEParameters : default params

@enduml
