@startuml
skinparam style strictuml
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true

title US-04 Input Parameters: Encoder parameter dataclasses + Trainer field setup

actor Developer
participant "<u>params:*Parameters</u>" as P
participant "<u>tr:Trainer</u>" as TR
participant "<u>factory:EncoderFactory</u>" as EF
participant "<u>if/of:InputField/OutputField</u>" as F

Developer -> P: Construct parameter dataclass\n(RDSEParameters/CategoryParameters/etc.)
Developer -> TR: add_input_field(name, size, params)
activate TR
TR -> TR: _encoder_type_from_params(params)
TR -> EF: create_encoder(encoder_type, **asdict(params))
EF --> TR: encoder instance
TR -> F: create InputField(..., encoder)
TR --> Developer: field registered in main_brain.fields
deactivate TR

Developer -> TR: add_output_field(name, size, params or motor_action)
TR -> F: create OutputField(...)
TR --> Developer: output field registered

Developer -> TR: add_column_field(name, num_columns, cells_per_column)
TR --> Developer: ColumnField registered

note over TR
Trainer enforces naming conventions:
*_input, *_output, *_column.
end note
@enduml
