@startuml
skinparam style strictuml
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true

title US-06 Train Brain: Trainer.train_full_brain()

actor Developer as Dev
participant "<u>tr:Trainer</u>" as TR
participant "<u>b:Brain</u>" as BR
participant "<u>if:InputField</u>" as IF
participant "<u>cf/vf:ColumnField/ValueField</u>" as CF

Dev -> TR: add_input_field(...)
Dev -> TR: add_output_field(...)
Dev -> TR: add_column_field(...)
Dev -> TR: train_full_brain(brain, dataset, steps)
activate TR

loop step in range(steps)
  TR -> TR: column_data = dataset[key][step % len(dataset[key])]
  TR -> TR: input_dict from configured trainer input fields
  TR -> BR: step(inputs=input_dict, learn=True)
  activate BR
  BR -> IF: encode(value) for each input
  BR -> CF: compute(learn=True) for column/value fields
  BR --> TR: behavior/action outputs
  deactivate BR
end

TR --> Dev: training complete (state stored in brain)
deactivate TR
@enduml
