@startuml
skinparam style strictuml
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true

title US-11 End-to-End Runtime Summary (Current Code)

actor Developer as Dev
participant "<u>adapter:EnvAdapter</u>" as EA
participant "<u>a:Agent</u>" as AG
participant "<u>b:Brain</u>" as BR
participant "<u>fields:Input/Column/Value/Output</u>" as F
participant "Gym Env" as ENV

Dev -> EA: reset_bridge()
EA -> ENV: reset()
ENV --> EA: obs, info
EA --> Dev: {obs, inputs, info}

Dev -> AG: step(learn=True|False)
activate AG
AG -> BR: step(inputs + reward, learn)
activate BR
BR -> F: encode_only(inputs)
BR -> F: compute_only(learn)
BR -> F: estimate_value(reward)
BR -> F: activate_apical_segments()
BR -> F: generate_behavior() -> output decode
BR --> AG: behavior dict

AG -> AG: select_action(...)
AG -> EA: step_bridge(action)
EA -> ENV: step(action)
ENV --> EA: obs, reward, terminated, truncated, info
EA --> AG: transition bridge
AG -> AG: update(...)\n(q_table TD or ValueField update path)
AG --> Dev: transition dict

deactivate BR
deactivate AG
@enduml
